name: Ubuntu CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  project: 'terrafirma'

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        name: [ubuntu-24.04]
        include:
          - name: ubuntu-24.04
            os: ubuntu-24.04
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Glm
      run: |
        sudo apt-get update
        sudo apt-get install libglm-dev -y

    - name: Create BUILD folder
      run: |
        mkdir ../build

    - name: Configure cmake
      working-directory: ../build
      run: cmake ${{ github.workspace }}

    - name: Build (Ubuntu)
      working-directory: ../build
      run: make

    - name: Archive build result
      uses: actions/upload-artifact@v4
      with:
        name: Binary ${{ matrix.name }}
        path: ${{ runner.workspace }}/build/src/${{ env.project }}
