name: MacOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  project: 'terrafirma'

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        name: [macos-6.4]
        include:
          - name: macos-6.4
            os: macos-latest
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Create BUILD folder
      run: |
        mkdir ../build

    - name: Configure cmake
      working-directory: ../build
      run: cmake ${{ github.workspace }}

    - name: Build (MacOS)
      working-directory: ../build
      run: make

    - name: Archive build result
      uses: actions/upload-artifact@v4
      with:
        name: Binary ${{ matrix.name }}
        path: ${{ runner.workspace }}/build/src/${{ env.project }}.dmg
