name: Windows CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  project: 'terrafirma'

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        name: [windows-6.4]
        include:
          - name: windows-6.4
            os: windows-2022
            msvc_toolset: '14.29'
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        toolset: ${{ matrix.msvc_toolset }}

    - name: Create BUILD folder
      run: |
        mkdir ../build
        mkdir ../deploy

    - name: Configure cmake
      working-directory: ../build
      run: cmake ${{ github.workspace }} -G "NMake Makefiles"

    - name: Build (Windows)
      working-directory: ../build
      shell: cmd
      run: nmake

    - name: Archive build result
      uses: actions/upload-artifact@v4
      with:
        name: Binary ${{ matrix.name }}
        path: ${{ runner.workspace }}/deploy/*

